### ISSUE TITLE
Validate a single IP or a series of IP without range

### ISSUE THREAD

**Issue by DavidePastore** [Respect/Validation#775]
I'm using the IP validator and I'd like to not use the range but a single IP or a series of IP.
For example:

```php
v::ip('127.0.0.1')->validate('127.0.0.1');
v::ip(['127.0.0.1', '127.0.0.2'])->validate('127.0.0.1');
```
You could say that I could just use `v::in(...)` but this is something connected to the IP world and I think this should be included in the validator.
It would be awesome if this library could support this.
Anyway I could help to make this change.

**Comment by henriquemoody** [comment]
With so many open issues, it's become hard to really know what's really important and what I have fixed already.

I'm closing issues that are too old, and I'm not really looking at them all. If this is still relevant, please comment here and I will reopen this issue.

Thanks for reporting! 🐼

**Comment by DavidePastore** [comment]
Hi @henriquemoody . As far as I can see this issue is still relevant so I think it could be reopened.
